### ISSUE TITLE
.gitignore missing and Contributing.md

### ISSUE THREAD

**Issue by magudb** [bifrostDK/ForumiOS#1]
Awesome, great idea with this project.
The repo is a little messy, you should remember to include a .gitignore file, for more on the swift [see here](https://github.com/github/gitignore/blob/master/Swift.gitignore)

And for you own fault you should include a contributing.md [see more here](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)
 
And i would look into setting up at Continous integration on Travis CI, this will help to ensure the project will build for everyone and help you enforce the projects standards. [more here](https://www.raywenderlich.com/109418/travis-ci-tutorial), if you need help with this write me.

Big up and keep up the nice work.

/Magnus

**Comment by Joachimdj** [comment]
Hey Magudb, Thanks for the comments. I will look into it as soon as possible.
